image: node:alpine

cache:
  key: node_modules
  paths:
    - node_modules/

stages:
  - deploy
  - notify

dev:
  stage: deploy
  script:
    - npm install
    - npm run build-develop
    - apk add --no-cache rsync sshpass openssh curl
    - mkdir -p ~/.ssh && chmod 777 ~/.ssh
    - sshpass -p $SSH_PASS_DEV rsync -riz --links -e "ssh -o StrictHostKeyChecking=no" $SSH_DIRECTORY_LOCAL_DEV $SSH_USER_DEV@$SSH_HOST_DEV:$SSH_DIRECTORY_REMOTE_DEV
    - sh .ci-notify.sh ✅
  only:
    - develop
  environment:
    name: Development

prod:
  stage: deploy
  script:
    - npm install
    - npm run build-master
    - apk add --no-cache rsync sshpass openssh curl
    - mkdir -p ~/.ssh && chmod 777 ~/.ssh
    - sshpass -p $SSH_PASS_PROD rsync -riz --links -e "ssh -o StrictHostKeyChecking=no" $SSH_DIRECTORY_LOCAL_PROD $SSH_USER_PROD@$SSH_HOST_PROD:$SSH_DIRECTORY_REMOTE_PROD
    - sh .ci-notify.sh ✅
  only:
    - master
  environment:
    name: Production

notify_error:
  stage: notify
  script:
    - sh .ci-error-notify.sh ❌
  when: on_failure #deploy fail