image: node:alpine

variables:
  PUBLIC_URL: /blockbuster-react
cache:
  paths:
    - node_modules

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - cp public/index.html public/404.html
    - mv public _public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master