image: node:alpine

cache:
  key: node_modules
  paths:
  - node_modules/

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - mkdir .public
  - cp -r dist/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
  environment:
    name: Pages